### ISSUE TITLE
Bundle error after installation

### ISSUE THREAD

**Issue by toutma** [ckfinder/ckfinder-symfony2-bundle#7] opened 2017-02-04 14:15 UTC
Hey,

According the documentation, I installed the bundle :
`composer require ckfinder/ckfinder-symfony2-bundle`

I enabled it on the AppKernel.php :
`new CKSource\Bundle\CKFinderBundle\CKSourceCKFinderBundle(),`

I tried to install CKfinder distribution :
`php app/console ckfinder:download`

But I have this error :
`Fatal error: Interface 'CKSource\CKFinder\Authentication\AuthenticationInterface' not found in /Users/XX/Sites/XX/vendor/ckfinder/ckfinder-symfony2-bundle/Authentication/AuthenticationInterface.php on line 20`

Any ideas ?

Thanks by advance.

**Comment by zaak** [comment] 2017-02-06 08:04
Hi @toutma. Could you please provide more info about bundles you use and your environment configuration? Unfortunately, I'm not able to reproduce this issue on a clean Symfony installation.

**Comment by igst** [comment] 2017-06-01 11:49
Hi,

I have the same problem.

the interface ckfinder-symfony3-bundle/Authentication/AuthenticationInterface within namespace CKSource\Bundle\CKFinderBundle\Authentication tries to "extend" the alias interface BaseAuthenticationInterface which is defined with namespace "CKSource\CKFinder\Authentication\AuthenticationInterface". 

Where is the file CKSource\CKFinder\Authentication\AuthenticationInterface placed in the directory tree?

**Comment by toutma** [comment] 2017-06-02 10:02
Hi, sorry for the missing response.  During the installation`php app/console ckfinder:download`I removed the interface :/ It was the only solution I found.

**Comment by igst** [comment] 2017-06-02 10:53
Maybe that's a workaround but in my opinion the code should be fixed. 

Now I realized that I'm not using ckfinder-symfony2-bundle but the ckfinder-symfony3-bundle with the same problem.

@zaak 
will this be fixed in the near future?

THX

**Comment by zaak** [comment] 2017-06-02 11:16
@igst @toutma: Could you guys please provide a bit more information about your environments? I've tried to reproduce this issue many times, but without luck. I'd be happy to know the exact version of PHP, Symfony and info bout any other bundles installed.

I have a wild guess that marking this service as `lazy` might help, but I'm unable to check it.

```yml
# CKSourceCKFinderBundle::Resources/config/services.yml

services:
    ckfinder.connector.auth:
        class: %ckfinder.connector.auth.class%
        calls:
            - [setContainer, ['@service_container']]
        lazy: true # <--

    ckfinder.connector:
        class: %ckfinder.connector.class%
        arguments: [%ckfinder.connector.config%]
        calls:
            - [offsetSet, ['authentication', '@ckfinder.connector.auth']]
        lazy: true # <--
```

**Comment by igst** [comment] 2017-06-02 12:35
@zaak 

Before I collect all possible information about my project, please have a look at ckfinder-symfony3-bundle/Authentication/AuthenticationInterface.php on line 15.

The mentioned namespace "use CKSource\CKFinder\Authentication\AuthenticationInterface as BaseAuthenticationInterface;" does not exist and this leads to our problem. 

If you think that this namespace exist, please let me know, where (in which php file) this namespace is defined.

Thanks!

**Comment by zaak** [comment] 2017-06-02 12:43
@igst: This namespace is defined in CKFinder code that you are about to download with `php app/console ckfinder:download` command, as it's not included in the bundle. CKFinder bundle services shouldn't be instantiated when this command is executed, but for some reason this happens. My guess is that some lazy loading mechanism tries to create a proxy wrapper for them, but this code i about to be downloaded! :D

**Comment by igst** [comment] 2017-06-02 13:43
@zaak 

Ah ok, that makes sense :-)

After your given hint I checked my installed bundles and a dependency of the jms/di-extra-bundle causes the error: jms/aop-bundle

Could you try to reproduce this case with installed AOP-Bundle in version 1.2.0. 

Thanks :-)

**Comment by zaak** [comment] 2017-06-03 08:56
Thanks @igst, that was really helpful! This issue is fixed in newest version of the bundle.

**Closed by zaak** 2017-06-03 08:56 UTC
